using Domain.Utils;

namespace Domain.Enumerators;

public enum BusinessErrorMessage
{
    [EnumDescription("USER_NOT_FOUND")]
    USER_NOT_FOUND = 1,

    [EnumDescription("INVALID_PASSWORD")]
    INVALID_PASSWORD = 2,

    [EnumDescription("NOT_FOUND")]
    NOT_FOUND = 3,

    [EnumDescription("INVALID_PAGE")]
    INVALID_PAGE = 4,

    [EnumDescription("INVALID_PARAMETER")]
    INVALID_PARAMETER = 5,

    [EnumDescription("DOCUMENT_ALREADY_USED")]
    DOCUMENT_ALREADY_USED = 6,

    [EnumDescription("NAME_ALREADY_USED")]
    NAME_ALREADY_USED = 7,

    [EnumDescription("BANK_ALREADY_EXISTS")]
    BANK_ALREADY_EXISTS = 8,

    [EnumDescription("BANK_NOT_FOUND")]
    BANK_NOT_FOUND = 9,

    [EnumDescription("INSTALLATION_NOT_BELONG_THIS_USER")]
    INSTALLATION_NOT_BELONG_THIS_USER = 10,

    [EnumDescription("INSTALLATION_ALREADY_EXISTS")]
    INSTALLATION_ALREADY_EXISTS = 11,

    [EnumDescription("FILE_ALREADY_EXISTS")]
    FILE_ALREADY_EXISTS = 12,

    [EnumDescription("FILE_NOT_FOUND")]
    FILE_NOT_FOUND = 13,

    [EnumDescription("SOMETHING_WENT_WRONG")]
    SOMETHING_WENT_WRONG = 14,

    [EnumDescription("PRECONTRACT_NOT_FOUND")]
    PRECONTRACT_NOT_FOUND = 15,

    [EnumDescription("INSTALLATION_NOT_FOUND")]
    INSTALLATION_NOT_FOUND = 16,

    [EnumDescription("INVOICE_ALREADY_HAS_A_CONTRACT")]
    INVOICE_ALREADY_HAS_A_CONTRACT = 17,

    [EnumDescription("CONTRACT_NOT_FOUND")]
    CONTRACT_NOT_FOUND = 18,

    [EnumDescription("PARTNER_NOT_FOUND")]
    PARTNER_NOT_FOUND = 19,

    [EnumDescription("BACKOFFICE_USER_ALREADY_EXISTS")]
    BACKOFFICE_USER_ALREADY_EXISTS = 20,

    [EnumDescription("BACKOFFICE_USER_NOT_FOUND")]
    BACKOFFICE_USER_NOT_FOUND = 21,

    [EnumDescription("BACKOFFICE_USER_NOT_AUTORIZED")]
    BACKOFFICE_USER_NOT_AUTORIZED = 22,

    [EnumDescription("GMP_ERROR")]
    GMP_ERROR = 23,

    [EnumDescription("SIMULATION_NOT_FOUND")]
    SIMULATION_NOT_FOUND = 24,

    [EnumDescription("UNSUPPORTED_DISTRIBUTOR")]
    UNSUPPORTED_DISTRIBUTOR = 25,

    [EnumDescription("MATERA_OFF")]
    MATERA_OFF = 26,

    [EnumDescription("CONTRACT_ERROR_CREATION")]
    CONTRACT_ERROR_CREATION = 27,

    [EnumDescription("VPN_ERROR")]
    VPN_ERROR = 28,

    [EnumDescription("USER_ALREADY_HAS_AN_ACTIVE_CONTRACT")]
    USER_ALREADY_HAS_AN_ACTIVE_CONTRACT = 29,

    [EnumDescription("USER_NAME_NOT_EQUAL_TO_GMP_NAME")]
    USER_NAME_NOT_EQUAL_TO_GMP_NAME = 30,

    [EnumDescription("RECOVERY_INVALID_TOKEN")]
    RECOVERY_INVALID_TOKEN = 31,

    [EnumDescription("USER_HAS_MORE_THAN_THREE_OPEN_INVOICES")]
    USER_HAS_MORE_THAN_THREE_OPEN_INVOICES = 32,

    [EnumDescription("USER_ALREADY_HAS_AN_ACTIVE_INSTALLMENT")]
    USER_ALREADY_HAS_AN_ACTIVE_INSTALLMENT = 33,

    [EnumDescription("LEAD_NOT_ALLOWED")]
    LEAD_NOT_ALLOWED = 34,

    [EnumDescription("USER_NOT_FOUND_OR_INVALID_PASSWORD")]
    USER_NOT_FOUND_OR_INVALID_PASSWORD = 35,

    [EnumDescription("BACKOFFICE_CLIENT_ALREADY_EXISTS_BLOCK_LIST")]
    BACKOFFICE_CLIENT_ALREADY_EXISTS_BLOCK_LIST = 36,

    [EnumDescription("CLIENT_IS_BLOCK_LIST")]
    CLIENT_IS_BLOCK_LIST = 37,

    [EnumDescription("CLIENT_IS_NOT_FOUND_BLOCK_LIST")]
    CLIENT_IS_NOT_FOUND_BLOCK_LIST = 38,

    [EnumDescription("EXPIRED_SIGN_TOKEN")]
    EXPIRED_SIGN_TOKEN = 39,

    [EnumDescription("GENERATE_EVIDENCE_FILES")]
    GENERATE_EVIDENCE_FILES = 40,

    [EnumDescription("INVALID_STEP")]
    INVALID_STEP = 41,

    [EnumDescription("INVALID_TOKEN")]
    INVALID_TOKEN = 42,

    [EnumDescription("INVALID_SHUTDOWN_DATE")]
    INVALID_SHUTDOWN_DATE = 44,

    [EnumDescription("DISTRIBUTOR_NOT_FOUND")]
    DISTRIBUTOR_NOT_FOUND = 46,

    [EnumDescription("DISTRIBUTOR_SHUTDOWN")]
    DISTRIBUTOR_SHUTDOWN = 45,

    [EnumDescription("INVALID_DOCUMENT_OR_RECOVERY_PASSWORD_TOKEN")]
    INVALID_DOCUMENT_OR_RECOVERY_PASSWORD_TOKEN = 43,

    [EnumDescription("USER_INVALID_DATE_OF_BIRTH")]
    USER_INVALID_DATE_OF_BIRTH = 47,

    [EnumDescription("USER_WITH_REPEAT_REGISTRATION_EMAIL")]
    USER_WITH_REPEAT_REGISTRATION_EMAIL = 48,

    [EnumDescription("USER_WITH_REPEAT_REGISTRATION_PHONE")]
    USER_WITH_REPEAT_REGISTRATION_PHONE = 49,

    [EnumDescription("USER_WITH_REPEAT_REGISTRATION_EMAIL_AND_PHONE")]
    USER_WITH_REPEAT_REGISTRATION_EMAIL_AND_PHONE = 50,

    [EnumDescription("CLIENT_ALREADY_REGISTERED_KOBANA")]
    CLIENT_ALREADY_REGISTERED_KOBANA = 51,

    [EnumDescription("GENERATE_FILE_SECURITY_INFO_NOT_FOUND")]
    GENERATE_FILE_SECURITY_INFO_NOT_FOUND = 52,

    [EnumDescription("GENERATE_FILE_PRE_CONTRACT_TOKEN_NOT_FOUND")]
    GENERATE_FILE_PRE_CONTRACT_TOKEN_NOT_FOUND = 53,

    [EnumDescription("CONTRACT_FILE_ALREADY_HAS_A_CONTRACT")]
    CONTRACT_FILE_ALREADY_HAS_A_CONTRACT = 54,

    [EnumDescription("PENDING_CONTRACT")]
    PENDING_CONTRACT = 55,

    [EnumDescription("PROPOSAL_NOT_SENT_TO_FINANCE")]
    PROPOSAL_NOT_SENT_TO_FINANCE = 56,

    [EnumDescription("ALREADY_EXISTS_CONTRACT_FOR_THIS_PRE_CONTRACT")]
    ALREADY_EXISTS_CONTRACT_FOR_THIS_PRE_CONTRACT = 57,

    [EnumDescription("INVALID_DDD_NUMBER")]
    INVALID_DDD_NUMBER = 58,

    [EnumDescription("CAF_VERIFICATION_STATUS")]
    CAF_VERIFICATION_STATUS = 59,

    [EnumDescription("ALREADY_EXISTS_CONTRACT_WITH_THIS_ID_FOR_THIS_BANK")]
    ALREADY_EXISTS_CONTRACT_WITH_THIS_ID_FOR_THIS_BANK = 60,

    [EnumDescription("SOME_VALUE_IS_MISSING")]
    SOME_VALUE_IS_MISSING = 61,

    [EnumDescription("INSTALLMENT_VALUE_GREATER_THAN_R$400")]
    INSTALLMENT_VALUE_GREATER_THAN_400 = 62,

    [EnumDescription("INSTALLMENT_VALUE_GREATER_THAN_INVOICE_AVERAGE")]
    INSTALLMENT_VALUE_GREATER_THAN_INVOICE_AVERAGE = 63,

    [EnumDescription("DISTRIBUTOR_NOT_ACTIVE_FOR_ALESTA")]
    DISTRIBUTOR_NOT_ACTIVE_FOR_ALESTA = 64,

    [EnumDescription("PARCELAMENTO_DISCO")]
    INSTALLMENT_DISCO = 65,

    [EnumDescription("BACKOFFICE_CITIES_ALREADY_EXISTS_BLOCK_LIST")]
    BACKOFFICE_CITIES_ALREADY_EXISTS_BLOCK_LIST = 66,

    [EnumDescription("CITY_IS_NOT_FOUND_BLOCK_LIST")]
    CITY_IS_NOT_FOUND_BLOCK_LIST = 67,

    [EnumDescription("STATE_CITY_IS_BLOCK_LIST")]
    STATE_CITY_IS_BLOCK_LIST = 68,

    [EnumDescription("DISTRIBUTOR_MICROCREDIT_INACTIVE")]
    DISTRIBUTOR_MICROCREDIT_INACTIVE = 69,

    [EnumDescription("BILLET_GENERATION_CONTROL_NOT_FOUND")]
    BILLET_GENERATION_CONTROL_NOT_FOUND = 70,

    [EnumDescription("CONTRACT_INSTALLMENT_NOT_FOUND")]
    CONTRACT_INSTALLMENT_NOT_FOUND = 71,

    [EnumDescription("DUE_DATE_IN_PAST")]
    DUE_DATE_IN_PAST = 72,

    [EnumDescription("CONTRACT_CANCELLED")]
    CONTRACT_CANCELLED = 73,

    [EnumDescription("GENERATE_DEBIT_CLEARANCE_LETTER_NOT_FOUND")]
    GENERATE_DEBIT_CLEARANCE_LETTER_NOT_FOUND = 74,

    [EnumDescription("EMAIL_MISMATCH_KOBANA")]
    EMAIL_MISMATCH_KOBANA = 75,

    [EnumDescription("USER_NOT_FOUND_KOBANA")]
    USER_NOT_FOUND_KOBANA = 76,

    [EnumDescription("COMMUNICATION_ERROR_KOBANA")]
    COMMUNICATION_ERROR_KOBANA = 77,

    [EnumDescription("GENERATING_CONTRACT_FILE")]
    GENERATING_CONTRACT_FILE = 78,

    [EnumDescription("ENUM_ERROR")]
    ENUM_ERROR = 79
}
